In [1]:
import pandas as pd
import numpy as np

In [59]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [14]:
show = pd.read_csv('2018,2019 공연.csv')
show.head()

,Unnamed: 0,Unnamed: 1,시작일,종료일,공연시설,공연장,객석수(석),Unnamed: 7
0,잠자는 숲속의 미녀,무용,2019.5.5,2019.5.5,대덕문화전당,대덕문화전당,536,대덕문화전당
1,이지은 피아노 독주회,클래식,2019.4.28,2019.4.28,꿈의숲아트센터,콘서트홀,301,NaN
2,"문화가 있는날 앙상블시리즈, 어린이를 위한 음악극 피터와 늑대 (5월)",연극,2019.5.29,2019.5.29,봉산문화회관,스페이스라온,90,NaN
3,"문화가 있는날 앙상블시리즈, 판소리소설과 현대춤 토끼전 (4월)",복합,2019.4.24,2019.4.24,봉산문화회관,스페이스라온,90,NaN
4,제2회 달보드레 정기연주회,클래식,2019.3.3,2019.3.3,포항시청,문화동 대잠홀,590,NaN

In [16]:
show.columns = ['name','genre','start','end','place','theater','seats','company']
show.head()

,name,genre,start,end,place,theater,seats,company
0,잠자는 숲속의 미녀,무용,2019.5.5,2019.5.5,대덕문화전당,대덕문화전당,536,대덕문화전당
1,이지은 피아노 독주회,클래식,2019.4.28,2019.4.28,꿈의숲아트센터,콘서트홀,301,NaN
2,"문화가 있는날 앙상블시리즈, 어린이를 위한 음악극 피터와 늑대 (5월)",연극,2019.5.29,2019.5.29,봉산문화회관,스페이스라온,90,NaN
3,"문화가 있는날 앙상블시리즈, 판소리소설과 현대춤 토끼전 (4월)",복합,2019.4.24,2019.4.24,봉산문화회관,스페이스라온,90,NaN
4,제2회 달보드레 정기연주회,클래식,2019.3.3,2019.3.3,포항시청,문화동 대잠홀,590,NaN

In [9]:
theater = pd.read_csv('final_merge.csv')
theater.head()

,Unnamed: 0,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,...,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
0,0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,...,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775
1,1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,...,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601
2,2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,...,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749
3,3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,...,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073
4,4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,...,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439

In [11]:
theater = theater[['name', 'n_theater', 'n_seats', 'theater_name',
       'n_seats2', 'attr', 'open', 'city', 'gu', 'address', 'CS2', 'PK6',
       'OL7', 'SW8', 'CT1', 'AT4', 'AD5', 'FD6', 'CE7', 'addr', 'lng', 'lat']]
theater.head()

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,...,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,...,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,...,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,...,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,...,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,...,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439

In [17]:
show.columns

Index(['name', 'genre', 'start', 'end', 'place', 'theater', 'seats',
       'company'],
      dtype='object')

In [27]:
show1 = show.copy()
show1 = show1[['place', 'theater','name','genre']]

In [80]:
show1.head()

      place  theater                                     name genre
0   대덕문화전당    대덕문화전당                               잠자는 숲속의 미녀    무용
1  꿈의숲아트센터      콘서트홀                              이지은 피아노 독주회   클래식
2   봉산문화회관    스페이스라온  문화가 있는날 앙상블시리즈, 어린이를 위한 음악극 피터와 늑대 (5월)    연극
3   봉산문화회관    스페이스라온      문화가 있는날 앙상블시리즈, 판소리소설과 현대춤 토끼전 (4월)    복합
4     포항시청   문화동 대잠홀                           제2회 달보드레 정기연주회   클래식

In [125]:
for i in range(len(theater)):
    theater.name[i] = theater.name[i].strip()
    theater.theater_name[i] = theater.theater_name[i].strip()

theater.head()

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439

In [82]:
for i in range(len(show1)):
    show1.place[i] = show1.place[i].strip()
    show1.theater[i] = show1.theater[i].strip()

show1.head()

     place  theater                                     name genre
0   대덕문화전당   대덕문화전당                               잠자는 숲속의 미녀    무용
1  꿈의숲아트센터     콘서트홀                              이지은 피아노 독주회   클래식
2   봉산문화회관   스페이스라온  문화가 있는날 앙상블시리즈, 어린이를 위한 음악극 피터와 늑대 (5월)    연극
3   봉산문화회관   스페이스라온      문화가 있는날 앙상블시리즈, 판소리소설과 현대춤 토끼전 (4월)    복합
4     포항시청  문화동 대잠홀                           제2회 달보드레 정기연주회   클래식

In [23]:
show.genre.unique()

array(['무용', '클래식', '연극', '복합', '오페라', '뮤지컬', '국악'], dtype=object)

In [33]:
len(show1.theater.unique())

909

In [31]:
show1.pivot_table(index=['place','theater'], columns='genre', aggfunc='count').reset_index().shape

(1223, 9)

In [84]:
show_genre = show1.pivot_table(index=['place','theater'], columns='genre', aggfunc='count', margins=True).reset_index()
show_genre.head()

                    place             theater name                            \
genre                                           국악   무용   뮤지컬   복합   연극  오페라
0               (재)경기문화재단                 다산홀  NaN  NaN   NaN  NaN  1.0  NaN
1                (재)영화의전당           비프씨어터(야외)  NaN  NaN   NaN  NaN  NaN  NaN
2                (재)영화의전당               하늘연극장  2.0  7.0   2.0  5.0  4.0  1.0
3        2001 아울렛키즈홀 [구로]    2001 아울렛키즈홀 [구로]  NaN  NaN  16.0  2.0  1.0  NaN
4      2001 아울렛키즈홀 [수원남문]  2001 아울렛키즈홀 [수원남문]  NaN  NaN  22.0  1.0  1.0  NaN


genre   클래식 All
0       NaN   1
1       1.0   1
2      21.0  42
3       1.0  20
4       NaN  24

In [85]:
show_genre_exp = show_genre.copy()
show_genre_exp.columns = ['place','theater','korea_opera','dance','musical','compound','play','opera','classic','total']
show_genre_exp.head()

,place,theater,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,다산홀,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1
1,(재)영화의전당,비프씨어터(야외),NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
2,(재)영화의전당,하늘연극장,2.0,7.0,2.0,5.0,4.0,1.0,21.0,42
3,2001 아울렛키즈홀 [구로],2001 아울렛키즈홀 [구로],NaN,NaN,16.0,2.0,1.0,NaN,1.0,20
4,2001 아울렛키즈홀 [수원남문],2001 아울렛키즈홀 [수원남문],NaN,NaN,22.0,1.0,1.0,NaN,NaN,24

In [41]:
show_genre_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1224 entries, 0 to 1223
Data columns (total 10 columns):
place          1224 non-null object
theater        1224 non-null object
korea_opera    198 non-null float64
dance          204 non-null float64
musical        697 non-null float64
compound       328 non-null float64
play           647 non-null float64
opera          126 non-null float64
classic        388 non-null float64
total          1224 non-null int64
dtypes: float64(7), int64(1), object(2)
memory usage: 95.8+ KB

In [86]:
show_genre_exp = show_genre_exp.fillna(0)
show_genre_exp.head()

,place,theater,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,다산홀,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
1,(재)영화의전당,비프씨어터(야외),0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,(재)영화의전당,하늘연극장,2.0,7.0,2.0,5.0,4.0,1.0,21.0,42
3,2001 아울렛키즈홀 [구로],2001 아울렛키즈홀 [구로],0.0,0.0,16.0,2.0,1.0,0.0,1.0,20
4,2001 아울렛키즈홀 [수원남문],2001 아울렛키즈홀 [수원남문],0.0,0.0,22.0,1.0,1.0,0.0,0.0,24

In [87]:
show_genre_exp.columns = ['name', 'theater_name', 'korea_opera', 'dance', 'musical', 'compound',
       'play', 'opera', 'classic', 'total']
show_genre_exp.head()

,name,theater_name,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,다산홀,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
1,(재)영화의전당,비프씨어터(야외),0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,(재)영화의전당,하늘연극장,2.0,7.0,2.0,5.0,4.0,1.0,21.0,42
3,2001 아울렛키즈홀 [구로],2001 아울렛키즈홀 [구로],0.0,0.0,16.0,2.0,1.0,0.0,1.0,20
4,2001 아울렛키즈홀 [수원남문],2001 아울렛키즈홀 [수원남문],0.0,0.0,22.0,1.0,1.0,0.0,0.0,24

In [49]:
print(theater.shape)
theater.head()

(1845, 22)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439

## theater에 join

In [126]:
df_merge = pd.merge(theater, show_genre_exp, on=['name','theater_name'], how='left')
print(df_merge.shape)
df_merge.head()

(1845, 30)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073,0.0,0.0,16.0,2.0,1.0,0.0,1.0,20.0
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439,0.0,0.0,22.0,1.0,1.0,0.0,0.0,24.0

In [127]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1845 entries, 0 to 1844
Data columns (total 30 columns):
name            1845 non-null object
n_theater       1845 non-null int64
n_seats         1845 non-null int64
theater_name    1845 non-null object
n_seats2        1845 non-null object
attr            1845 non-null object
open            1845 non-null int64
city            1845 non-null object
gu              1845 non-null object
address         1845 non-null object
CS2             1845 non-null float64
PK6             1845 non-null float64
OL7             1845 non-null float64
SW8             1845 non-null float64
CT1             1845 non-null float64
AT4             1845 non-null float64
AD5             1845 non-null float64
FD6             1845 non-null float64
CE7             1845 non-null float64
addr            1845 non-null object
lng             1845 non-null float64
lat             1845 non-null float64
korea_opera     1137 non-null float64
dance           1137 non-null float64
musical         1137 non-null float64
compound        1137 non-null float64
play            1137 non-null float64
opera           1137 non-null float64
classic         1137 non-null float64
total           1137 non-null float64
dtypes: float64(19), int64(3), object(8)
memory usage: 446.8+ KB

In [128]:
1224 - 1137

87

In [1]:
a = 1845 - 1224
b = a/1845 * 100
print('theater에는 있고 show에는 없는 행 갯수 :',a)
print('na 비율 :', b, '%')

theater에는 있고 show에는 없는 행 갯수 : 621
na 비율 : 33.65853658536586 %

In [132]:
a = 1845 - 1137
b = a/1845 * 100
print('theater에는 있고 show에는 없는 행 갯수 :',a)
print('na 비율 :', b, '%')

theater에는 있고 show에는 없는 행 갯수 : 708
na 비율 : 38.3739837398374 %

## outer로 join

In [129]:
df_merge_out = pd.merge(theater, show_genre_exp, on=['name','theater_name'], how='outer')
print(df_merge_out.shape)
df_merge_out.head()

(1932, 30)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,1.0,154.0,다산홀,154,공공(기타),2001.0,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1M SPACE,1.0,0.0,1M SPACE,0,민간(대학로 외),2019.0,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1m클래식아트홀,1.0,130.0,1m클래식아트홀,130,민간(대학로),2007.0,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001 아울렛키즈홀 [구로],1.0,100.0,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017.0,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073,0.0,0.0,16.0,2.0,1.0,0.0,1.0,20.0
4,2001 아울렛키즈홀 [수원남문],1.0,100.0,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005.0,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439,0.0,0.0,22.0,1.0,1.0,0.0,0.0,24.0

In [130]:
df_merge_out.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1932 entries, 0 to 1931
Data columns (total 30 columns):
name            1932 non-null object
n_theater       1845 non-null float64
n_seats         1845 non-null float64
theater_name    1932 non-null object
n_seats2        1845 non-null object
attr            1845 non-null object
open            1845 non-null float64
city            1845 non-null object
gu              1845 non-null object
address         1845 non-null object
CS2             1845 non-null float64
PK6             1845 non-null float64
OL7             1845 non-null float64
SW8             1845 non-null float64
CT1             1845 non-null float64
AT4             1845 non-null float64
AD5             1845 non-null float64
FD6             1845 non-null float64
CE7             1845 non-null float64
addr            1845 non-null object
lng             1845 non-null float64
lat             1845 non-null float64
korea_opera     1224 non-null float64
dance           1224 non-null float64
musical         1224 non-null float64
compound        1224 non-null float64
play            1224 non-null float64
opera           1224 non-null float64
classic         1224 non-null float64
total           1224 non-null float64
dtypes: float64(22), object(8)
memory usage: 467.9+ KB

In [133]:
df_merge_out.tail(100)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
1832,현대카드 언더스테이지,2.0,375.0,스튜디오,350,민간(대학로 외),2015.0,서울,용산구,서울특별시 용산구 이태원로 246,11.0,28.0,1.0,1.0,28.0,2.0,12.0,317.0,123.0,서울특별시 용산구 이태원로 246,127.000702,37.536636,1.0,1.0,0.0,3.0,0.0,0.0,0.0,5.0
1833,현대카드 언더스테이지,2.0,375.0,Vinyl ＆ Plastic(뮤직라이브러리),25,민간(대학로 외),2015.0,서울,용산구,서울특별시 용산구 이태원로 246,11.0,28.0,1.0,1.0,28.0,2.0,12.0,317.0,123.0,서울특별시 용산구 이태원로 246,127.000702,37.536636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1834,홍익대 대학로 아트센터,2.0,852.0,대극장,702,민간(대학로),2013.0,서울,종로구,서울특별시 종로구 대학로 57,26.0,43.0,0.0,0.0,51.0,3.0,17.0,304.0,96.0,서울특별시 종로구 대학로 57,127.001450,37.576559,0.0,0.0,9.0,0.0,0.0,0.0,0.0,9.0
1835,홍익대 대학로 아트센터,2.0,852.0,소극장,150,민간(대학로),2013.0,서울,종로구,서울특별시 종로구 대학로 57,26.0,43.0,0.0,0.0,51.0,3.0,17.0,304.0,96.0,서울특별시 종로구 대학로 57,127.001450,37.576559,0.0,0.0,0.0,0.0,17.0,0.0,0.0,17.0
1836,홍주문화회관,2.0,715.0,대공연장,615,공공(문예회관),1988.0,충남,홍성군,충청남도 홍성군 홍성읍 내포로 164,3.0,6.0,5.0,0.0,3.0,3.0,1.0,51.0,10.0,충청남도 홍성군 홍성읍 내포로 164,126.651896,36.594770,0.0,0.0,4.0,0.0,1.0,0.0,1.0,6.0
1837,홍주문화회관,2.0,715.0,소공연장,100,공공(문예회관),1988.0,충남,홍성군,충청남도 홍성군 홍성읍 내포로 164,3.0,6.0,5.0,0.0,3.0,3.0,1.0,51.0,10.0,충청남도 홍성군 홍성읍 내포로 164,126.651896,36.594770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1838,화순 하니움 문화스포츠센터,2.0,893.0,적벽실(대강당),725,공공(기타),2009.0,전남,화순군,전라남도 화순군 학포로 2698 - 0 이용대체육관,1.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0,5.0,전라남도 화순군 학포로 2698 - 0 이용대체육관,126.968613,35.050124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1839,화순 하니움 문화스포츠센터,2.0,893.0,만연홀(소공연장),168,공공(기타),2009.0,전남,화순군,전라남도 화순군 학포로 2698 - 0 이용대체육관,1.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0,5.0,전라남도 화순군 학포로 2698 - 0 이용대체육관,126.968613,35.050124,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1840,후용공연예술센터,2.0,320.0,교실극장,120,민간(대학로 외),2001.0,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0
1841,후용공연예술센터,2.0,320.0,야외공연장,200,민간(대학로 외),2001.0,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1842,흰물결아트센터,3.0,978.0,화이트홀,475,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,1.0,2.0,0.0,0.0,0.0,2.0,5.0
1843,흰물결아트센터,3.0,978.0,아트홀,200,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1844,흰물결아트센터,3.0,978.0,예술극장,303,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1845,BNK부산은행 조은극장,NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1846,KT&G 상상마당 라이브홀,NaN,NaN,상상마당 라이브홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1847,TPO Gallery(부산인도네시아센터),NaN,NaN,TPO Gallery(부산인도네시아센터),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1848,가온아트홀 [부산],NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1849,갤러리롤랑,NaN,NaN,갤러리롤랑,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1850,경기상상캠퍼스 M3,NaN,NaN,"교육1964, 공간1986",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1851,경기상상캠퍼스 M3,NaN,NaN,"멀티벙커, 공간1986",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1852,"고양어울림누리, 고양아람누리",NaN,NaN,"어울림극장, 아람극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1853,과천시민회관,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1854,광명시 광명 5동 일대,NaN,NaN,광명 5동 일대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1855,광운대학교 동해문화예술관,NaN,NaN,소극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1856,구름아래소극장,NaN,NaN,구름아래소극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1857,그랜드하얏트서울,NaN,NaN,그랜드 볼룸,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1858,"극장용, 국립중앙박물관",NaN,NaN,극장용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1859,"김천시문화예술회관, 김천시립문화회관",NaN,NaN,"대공연장, 김천시립문화회관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1860,노원어린이극장(구.노원어울림극장),NaN,NaN,노원어린이극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,1.0,0.0,3.0,6.0
1861,당진문예의전당,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1862,대구콘서트하우스,NaN,NaN,"챔버홀(소공연장), 그랜드홀(대공연장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1863,대백프라자,NaN,NaN,"프라임홀, 레오문화홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,4.0,0.0,0.0,6.0
1864,"대전 대덕구 청소년수련관, 대덕청소년수련관",NaN,NaN,"대전 대덕구 청소년수련관, 강당",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1865,대전평송청소년문화센터,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1866,"대학로스타시티, KBS 수원아트홀",NaN,NaN,"타이니앨리스 (구 아트홀 마리카2관), KBS 수원아트홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1867,"더케이호텔 [서울], 더케이아트홀",NaN,NaN,더케이아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1868,"더페이지 갤러리, 더 서울라이티움 (갤러리아포레 G층 전용관)",NaN,NaN,더페이지 갤러리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1869,동래문화회관,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1870,디큐브아트센터,NaN,NaN,"스페이스 신도림, 디큐브씨어터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3.0,0.0,0.0,0.0,0.0,3.0
1871,뚝섬플레이스,NaN,NaN,뚝섬플레이스,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1872,"레몬트리소극장, 가온아트홀 [부산]",NaN,NaN,"레몬트리소극장, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1873,명작극장 (구 아츠플레이씨어터),NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1874,명작극장 (구 아츠플레이씨어터),NaN,NaN,"명작극장 (구 아츠플레이씨어터), 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0
1875,명작극장 (구 아츠플레이씨어터),NaN,NaN,"명작극장 (구 아츠플레이씨어터), 2관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7.0,0.0,1.0,0.0,0.0,8.0
1876,"명작극장 (구 아츠플레이씨어터), 마루아트홀",NaN,NaN,마루아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,2.0,0.0,0.0,4.0
1877,무대륙,NaN,NaN,무대륙,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1878,문경문화예술회관,NaN,NaN,"문희아트홀, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1879,미마지아트센터,NaN,NaN,"풀빛극장(오아시스극장), 눈빛극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1880,"민송아트홀 (구. 브로드웨이아트홀), 굿씨어터",NaN,NaN,1관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1881,"민송아트홀 (구. 브로드웨이아트홀), 굿씨어터",NaN,NaN,2관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1882,봄날아트홀(구. 아리랑소극장),NaN,NaN,"2관(지하2층), 1관(지하1층)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1883,부산문화회관,NaN,NaN,"중극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1884,"부천시민회관, 미마지아트센터",NaN,NaN,"풀빛극장(오아시스극장), 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1885,부평아트센터,NaN,NaN,"해누리극장, 달누리극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1886,"브러쉬씨어터, 롯데서울숲IT캐슬",NaN,NaN,"공연장, 공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1887,생기 스튜디오,NaN,NaN,생기 스튜디오,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1888,서산시문화회관,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1889,"서울주문화센터, 동양예술극장(구. 아트센터K)",NaN,NaN,"대공연장, 1관(네모극장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1890,서포초등학교,NaN,NaN,강당,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1891,"세라믹팔레스홀, 당진문예의전당",NaN,NaN,"세라믹팔레스홀, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1892,송파브이아트홀,NaN,NaN,송파브이아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1893,수성아트피아,NaN,NaN,"용지홀, 무학홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1894,"순위아트홀1관 [대학로], 순위아트홀(구. 네오아트홀) [강남]",NaN,NaN,순위아트홀1관 [대학로],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1895,스페이스바움,NaN,NaN,스페이스바움,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1896,"씨마크호텔 [강릉], 강릉아트센터(구. 강릉문화예술관)",NaN,NaN,야외공연장 아레나,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1897,"안산문화예술의전당, 그랜드힐튼호텔",NaN,NaN,"컨벤션홀, 달맞이극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1898,어울아트센터(구. 대구북구문예회관),NaN,NaN,"함지홀(대공연장), 오봉홀(소공연장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1899,"여우별아트홀, 낙산씨어터",NaN,NaN,"여우별아트홀, 낙산씨어터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1900,"영산아트홀, 세종문화회관",NaN,NaN,"영산아트홀, 세종체임버홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1901,올림픽공원,NaN,NaN,"야외(88잔디마당), KSPO DOME(체조경기장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1902,우나앤쿠,NaN,NaN,우나앤쿠,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1903,울산문화예술회관,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
1904,"울진문화예술회관, 울진군문화센터",NaN,NaN,"울진문화예술회관, 울진군문화센터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1905,유앤아이센터 (화성아트홀),NaN,NaN,화성아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,5.0,0.0,1.0,0.0,4.0,11.0
1906,윤당아트홀,NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1907,"이화여자대학교 삼성홀, 이화여자대학교 김영의홀",NaN,NaN,이화여자대학교 삼성홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1908,"익스트림씨어터 2관, 내유외강씨어터(구. 익스트림씨어터 1관)",NaN,NaN,익스트림씨어터 2관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1909,"인제하늘내린센터, 알펜시아 리조트",NaN,NaN,"뮤직텐트, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1910,인천문화예술회관,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
1911,"제주문예회관, 은평문화예술회관",NaN,NaN,"대극장, 공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1912,추계예술대학교 황신덕기념관,NaN,NaN,콘서트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1913,"축제소극장 [창원](구. 창원아트팩토리), 만수아트홀",NaN,NaN,만수아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1914,"축제소극장 [창원](구. 창원아트팩토리), 만수아트홀",NaN,NaN,"만수아트홀, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1915,춘천인형극장,NaN,NaN,"하늘극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0
1916,춘천인형극장,NaN,NaN,"하늘극장, 바우극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0
1917,춘천인형극장,NaN,NaN,"하늘극장, 코코극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0
1918,티오엠씨어터(구. 문화공간필링),NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1919,파주 프로방스 마술극장,NaN,NaN,파주 프로방스 마술극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1920,"파주 프로방스 마술극장, 맛있는 극장",NaN,NaN,"파주 프로방스 마술극장, 맛있는 극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1921,포천반월아트홀,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1922,폼텍웍스홀,NaN,NaN,폼텍웍스홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1923,"하마씨어터(구. 가든씨어터), 대학로 극장가게 (구. 문씨어터, 지구인씨어터)",NaN,NaN,"하마씨어터(구. 가든씨어터), 문씨어터 (구. 지구인씨어터)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1924,"하마씨어터(구. 가든씨어터), 세종문화회관, 드림시어터 [대학로]",NaN,NaN,"하마씨어터(구. 가든씨어터), S씨어터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1925,"한국소리문화의전당, 전북대학교 삼성문화회관",NaN,NaN,"모악당, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1926,한성아트홀(구. 인켈아트홀),NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1927,"해바라기소극장(구. 훈아트홀), 해바라기소극장 [부산]",NaN,NaN,"해바라기소극장(구. 훈아트홀), 해바라기소극장 [부산]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1928,현대백화점 문화홀 [대구],NaN,NaN,"토파즈홀, 문화홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1929,"현대백화점 문화홀 [킨텍스], 솔가람아트홀",NaN,NaN,"문화홀 (9층), 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1930,"홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...",NaN,NaN,"홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1931,All,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,853.0,817.0,3350.0,654.0,2840.0,369.0,5056.0,13939.0

In [153]:
theater[theater.name=='김천시립문화회관']

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
1285,당진문예의전당,3,1401,대공연장,"1,001",공공(문예회관),2005,충남,당진시,충청남도 당진시 무수동2길 25-21,20.0,1.0,0.0,0.0,4.0,0.0,0.0,165.0,15.0,충청남도 당진시 무수동2길 25-21,126.637483,36.889723
1286,당진문예의전당,3,1401,소공연장,300,공공(문예회관),2005,충남,당진시,충청남도 당진시 무수동2길 25-21,20.0,1.0,0.0,0.0,4.0,0.0,0.0,165.0,15.0,충청남도 당진시 무수동2길 25-21,126.637483,36.889723
1287,당진문예의전당,3,1401,야외공연장,100,공공(문예회관),2005,충남,당진시,충청남도 당진시 무수동2길 25-21,20.0,1.0,0.0,0.0,4.0,0.0,0.0,165.0,15.0,충청남도 당진시 무수동2길 25-21,126.637483,36.889723

'BNK부산은행 조은극장' 상영관이 두개 합쳐져있다 <br>
'KT&G 상상마당 라이브홀' 상영시설 데이터에 없다 <br>
'TPO Gallery(부산인도네시아센터)' 상영시설 데이터에 없다 <br>
'가온아트홀 [부산]' 상영관이 두개 합쳐져있다 <br>
'경기상상캠퍼스 M3' 상영관이 두개 합쳐져있다 <br>
'고양어울림누리, 고양아람누리' 상영시설이 두개 합쳐져있다 <br>
'과천시민회관' 상영관이 두개 합쳐져있다 <br>
'광명시 광명 5동 일대' 상영시설 데이터에 없다 <br>
'광운대학교 동해문화예술관' 상영시설 데이터에 없다 <br>
'구름아래소극장' 상영시설 데이터에 없다 <br>
'그랜드하얏트서울' 상영시설 데이터에 없다 <br>
'극장용, 국립중앙박물관' 국립중앙박물관은 있는데 '극장용, 국립중앙박물관'은 없다 / 뮤지컬 2개 <br>
'김천시문화예술회관, 김천시립문화회관' 상영시설이 두개 합쳐져있다 두개 거리도 꽤 먼데<br>
'당진문예의전당' 상영관이 두개 합쳐져있다 <br>

In [149]:
show1[show1.place=='극장용, 국립중앙박물관']

              place theater                      name genre
6342   극장용, 국립중앙박물관     극장용  세계문명탐험대: 태양의 나라 이집트 [서울]   뮤지컬
11873  극장용, 국립중앙박물관     극장용                       보물섬   뮤지컬

In [155]:
theater.to_csv('theater.csv', index=False, encoding='utf-8')
show1.to_csv('show_name_genre.csv', index=False, encoding='utf-8')
df_merge.to_csv('df_merge_theater.csv', index=False, encoding='utf-8')
df_merge_out.to_csv('df_merge_outer.csv', index=False, encoding='utf-8')