In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.set_option('display.max_columns', 500)
pd.set_option('display.max_rows', 500)

In [3]:
show = pd.read_csv('2018,2019 공연.csv')
show.columns = ['name','genre','start','end','place','theater','seats','company']
show.head()

,name,genre,start,end,place,theater,seats,company
0,잠자는 숲속의 미녀,무용,2019.5.5,2019.5.5,대덕문화전당,대덕문화전당,536,대덕문화전당
1,이지은 피아노 독주회,클래식,2019.4.28,2019.4.28,꿈의숲아트센터,콘서트홀,301,NaN
2,"문화가 있는날 앙상블시리즈, 어린이를 위한 음악극 피터와 늑대 (5월)",연극,2019.5.29,2019.5.29,봉산문화회관,스페이스라온,90,NaN
3,"문화가 있는날 앙상블시리즈, 판소리소설과 현대춤 토끼전 (4월)",복합,2019.4.24,2019.4.24,봉산문화회관,스페이스라온,90,NaN
4,제2회 달보드레 정기연주회,클래식,2019.3.3,2019.3.3,포항시청,문화동 대잠홀,590,NaN

In [4]:
theater = pd.read_csv('final_merge.csv')
theater = theater[['name', 'n_theater', 'n_seats', 'theater_name',
       'n_seats2', 'attr', 'open', 'city', 'gu', 'address', 'CS2', 'PK6',
       'OL7', 'SW8', 'CT1', 'AT4', 'AD5', 'FD6', 'CE7', 'addr', 'lng', 'lat']]
theater.head()

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439

In [5]:
for i in range(len(theater)):
    theater.name[i] = theater.name[i].strip()
    theater.theater_name[i] = theater.theater_name[i].strip()

theater.head()

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439

In [17]:
df2 = pd.DataFrame(index=range(0,1000),columns=['place', 'theater','name','genre'])
df2.head()

  place theater name genre
0   NaN     NaN  NaN   NaN
1   NaN     NaN  NaN   NaN
2   NaN     NaN  NaN   NaN
3   NaN     NaN  NaN   NaN
4   NaN     NaN  NaN   NaN

In [3]:
show = pd.read_csv('show_name_genre.csv')
show.head()

     place  theater                                     name genre
0   대덕문화전당   대덕문화전당                               잠자는 숲속의 미녀    무용
1  꿈의숲아트센터     콘서트홀                              이지은 피아노 독주회   클래식
2   봉산문화회관   스페이스라온  문화가 있는날 앙상블시리즈, 어린이를 위한 음악극 피터와 늑대 (5월)    연극
3   봉산문화회관   스페이스라온      문화가 있는날 앙상블시리즈, 판소리소설과 현대춤 토끼전 (4월)    복합
4     포항시청  문화동 대잠홀                           제2회 달보드레 정기연주회   클래식

In [4]:
theater = pd.read_csv('theater.csv')

In [5]:
theater.columns

Index(['name', 'n_theater', 'n_seats', 'theater_name', 'n_seats2', 'attr',
       'open', 'city', 'gu', 'address', 'CS2', 'PK6', 'OL7', 'SW8', 'CT1',
       'AT4', 'AD5', 'FD6', 'CE7', 'addr', 'lng', 'lat'],
      dtype='object')

In [220]:
theater[theater.name == '홍대난타극장(구. 뮤직쇼웨딩 전용관)']

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
1059,홍대난타극장(구. 뮤직쇼웨딩 전용관),1,331,홍대난타극장(구. 뮤직쇼웨딩 전용관),331,민간(대학로 외),2011,서울,마포구,서울특별시 마포구 양화로16길 29,52.0,76.0,0.0,1.0,56.0,7.0,57.0,1463.0,577.0,서울특별시 마포구 양화로16길 29,126.921175,37.553196

In [26]:
merged_out = pd.read_csv('df_merge_outer.csv')
merged_out.tail(100)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
1832,현대카드 언더스테이지,2.0,375.0,스튜디오,350,민간(대학로 외),2015.0,서울,용산구,서울특별시 용산구 이태원로 246,11.0,28.0,1.0,1.0,28.0,2.0,12.0,317.0,123.0,서울특별시 용산구 이태원로 246,127.000702,37.536636,1.0,1.0,0.0,3.0,0.0,0.0,0.0,5.0
1833,현대카드 언더스테이지,2.0,375.0,Vinyl ＆ Plastic(뮤직라이브러리),25,민간(대학로 외),2015.0,서울,용산구,서울특별시 용산구 이태원로 246,11.0,28.0,1.0,1.0,28.0,2.0,12.0,317.0,123.0,서울특별시 용산구 이태원로 246,127.000702,37.536636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1834,홍익대 대학로 아트센터,2.0,852.0,대극장,702,민간(대학로),2013.0,서울,종로구,서울특별시 종로구 대학로 57,26.0,43.0,0.0,0.0,51.0,3.0,17.0,304.0,96.0,서울특별시 종로구 대학로 57,127.001450,37.576559,0.0,0.0,9.0,0.0,0.0,0.0,0.0,9.0
1835,홍익대 대학로 아트센터,2.0,852.0,소극장,150,민간(대학로),2013.0,서울,종로구,서울특별시 종로구 대학로 57,26.0,43.0,0.0,0.0,51.0,3.0,17.0,304.0,96.0,서울특별시 종로구 대학로 57,127.001450,37.576559,0.0,0.0,0.0,0.0,17.0,0.0,0.0,17.0
1836,홍주문화회관,2.0,715.0,대공연장,615,공공(문예회관),1988.0,충남,홍성군,충청남도 홍성군 홍성읍 내포로 164,3.0,6.0,5.0,0.0,3.0,3.0,1.0,51.0,10.0,충청남도 홍성군 홍성읍 내포로 164,126.651896,36.594770,0.0,0.0,4.0,0.0,1.0,0.0,1.0,6.0
1837,홍주문화회관,2.0,715.0,소공연장,100,공공(문예회관),1988.0,충남,홍성군,충청남도 홍성군 홍성읍 내포로 164,3.0,6.0,5.0,0.0,3.0,3.0,1.0,51.0,10.0,충청남도 홍성군 홍성읍 내포로 164,126.651896,36.594770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1838,화순 하니움 문화스포츠센터,2.0,893.0,적벽실(대강당),725,공공(기타),2009.0,전남,화순군,전라남도 화순군 학포로 2698 - 0 이용대체육관,1.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0,5.0,전라남도 화순군 학포로 2698 - 0 이용대체육관,126.968613,35.050124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1839,화순 하니움 문화스포츠센터,2.0,893.0,만연홀(소공연장),168,공공(기타),2009.0,전남,화순군,전라남도 화순군 학포로 2698 - 0 이용대체육관,1.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0,5.0,전라남도 화순군 학포로 2698 - 0 이용대체육관,126.968613,35.050124,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1840,후용공연예술센터,2.0,320.0,교실극장,120,민간(대학로 외),2001.0,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0
1841,후용공연예술센터,2.0,320.0,야외공연장,200,민간(대학로 외),2001.0,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1842,흰물결아트센터,3.0,978.0,화이트홀,475,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,1.0,2.0,0.0,0.0,0.0,2.0,5.0
1843,흰물결아트센터,3.0,978.0,아트홀,200,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1844,흰물결아트센터,3.0,978.0,예술극장,303,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1845,BNK부산은행 조은극장,NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1846,KT&G 상상마당 라이브홀,NaN,NaN,상상마당 라이브홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1847,TPO Gallery(부산인도네시아센터),NaN,NaN,TPO Gallery(부산인도네시아센터),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1848,가온아트홀 [부산],NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1849,갤러리롤랑,NaN,NaN,갤러리롤랑,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1850,경기상상캠퍼스 M3,NaN,NaN,"교육1964, 공간1986",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1851,경기상상캠퍼스 M3,NaN,NaN,"멀티벙커, 공간1986",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1852,"고양어울림누리, 고양아람누리",NaN,NaN,"어울림극장, 아람극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1853,과천시민회관,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1854,광명시 광명 5동 일대,NaN,NaN,광명 5동 일대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1855,광운대학교 동해문화예술관,NaN,NaN,소극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1856,구름아래소극장,NaN,NaN,구름아래소극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1857,그랜드하얏트서울,NaN,NaN,그랜드 볼룸,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1858,"극장용, 국립중앙박물관",NaN,NaN,극장용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1859,"김천시문화예술회관, 김천시립문화회관",NaN,NaN,"대공연장, 김천시립문화회관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1860,노원어린이극장(구.노원어울림극장),NaN,NaN,노원어린이극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,1.0,0.0,3.0,6.0
1861,당진문예의전당,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1862,대구콘서트하우스,NaN,NaN,"챔버홀(소공연장), 그랜드홀(대공연장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1863,대백프라자,NaN,NaN,"프라임홀, 레오문화홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,4.0,0.0,0.0,6.0
1864,"대전 대덕구 청소년수련관, 대덕청소년수련관",NaN,NaN,"대전 대덕구 청소년수련관, 강당",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1865,대전평송청소년문화센터,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1866,"대학로스타시티, KBS 수원아트홀",NaN,NaN,"타이니앨리스 (구 아트홀 마리카2관), KBS 수원아트홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1867,"더케이호텔 [서울], 더케이아트홀",NaN,NaN,더케이아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1868,"더페이지 갤러리, 더 서울라이티움 (갤러리아포레 G층 전용관)",NaN,NaN,더페이지 갤러리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1869,동래문화회관,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1870,디큐브아트센터,NaN,NaN,"스페이스 신도림, 디큐브씨어터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3.0,0.0,0.0,0.0,0.0,3.0
1871,뚝섬플레이스,NaN,NaN,뚝섬플레이스,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1872,"레몬트리소극장, 가온아트홀 [부산]",NaN,NaN,"레몬트리소극장, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1873,명작극장 (구 아츠플레이씨어터),NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1874,명작극장 (구 아츠플레이씨어터),NaN,NaN,"명작극장 (구 아츠플레이씨어터), 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0
1875,명작극장 (구 아츠플레이씨어터),NaN,NaN,"명작극장 (구 아츠플레이씨어터), 2관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7.0,0.0,1.0,0.0,0.0,8.0
1876,"명작극장 (구 아츠플레이씨어터), 마루아트홀",NaN,NaN,마루아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,2.0,0.0,0.0,4.0
1877,무대륙,NaN,NaN,무대륙,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1878,문경문화예술회관,NaN,NaN,"문희아트홀, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1879,미마지아트센터,NaN,NaN,"풀빛극장(오아시스극장), 눈빛극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1880,"민송아트홀 (구. 브로드웨이아트홀), 굿씨어터",NaN,NaN,1관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1881,"민송아트홀 (구. 브로드웨이아트홀), 굿씨어터",NaN,NaN,2관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1882,봄날아트홀(구. 아리랑소극장),NaN,NaN,"2관(지하2층), 1관(지하1층)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1883,부산문화회관,NaN,NaN,"중극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0
1884,"부천시민회관, 미마지아트센터",NaN,NaN,"풀빛극장(오아시스극장), 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1885,부평아트센터,NaN,NaN,"해누리극장, 달누리극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1886,"브러쉬씨어터, 롯데서울숲IT캐슬",NaN,NaN,"공연장, 공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1887,생기 스튜디오,NaN,NaN,생기 스튜디오,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1888,서산시문화회관,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1889,"서울주문화센터, 동양예술극장(구. 아트센터K)",NaN,NaN,"대공연장, 1관(네모극장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1890,서포초등학교,NaN,NaN,강당,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1891,"세라믹팔레스홀, 당진문예의전당",NaN,NaN,"세라믹팔레스홀, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1892,송파브이아트홀,NaN,NaN,송파브이아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1893,수성아트피아,NaN,NaN,"용지홀, 무학홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1894,"순위아트홀1관 [대학로], 순위아트홀(구. 네오아트홀) [강남]",NaN,NaN,순위아트홀1관 [대학로],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1895,스페이스바움,NaN,NaN,스페이스바움,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1896,"씨마크호텔 [강릉], 강릉아트센터(구. 강릉문화예술관)",NaN,NaN,야외공연장 아레나,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1897,"안산문화예술의전당, 그랜드힐튼호텔",NaN,NaN,"컨벤션홀, 달맞이극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1898,어울아트센터(구. 대구북구문예회관),NaN,NaN,"함지홀(대공연장), 오봉홀(소공연장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1899,"여우별아트홀, 낙산씨어터",NaN,NaN,"여우별아트홀, 낙산씨어터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1900,"영산아트홀, 세종문화회관",NaN,NaN,"영산아트홀, 세종체임버홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1901,올림픽공원,NaN,NaN,"야외(88잔디마당), KSPO DOME(체조경기장)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1902,우나앤쿠,NaN,NaN,우나앤쿠,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1903,울산문화예술회관,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
1904,"울진문화예술회관, 울진군문화센터",NaN,NaN,"울진문화예술회관, 울진군문화센터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1905,유앤아이센터 (화성아트홀),NaN,NaN,화성아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,5.0,0.0,1.0,0.0,4.0,11.0
1906,윤당아트홀,NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1907,"이화여자대학교 삼성홀, 이화여자대학교 김영의홀",NaN,NaN,이화여자대학교 삼성홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1908,"익스트림씨어터 2관, 내유외강씨어터(구. 익스트림씨어터 1관)",NaN,NaN,익스트림씨어터 2관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1909,"인제하늘내린센터, 알펜시아 리조트",NaN,NaN,"뮤직텐트, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1910,인천문화예술회관,NaN,NaN,"소공연장, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,1.0,2.0
1911,"제주문예회관, 은평문화예술회관",NaN,NaN,"대극장, 공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1912,추계예술대학교 황신덕기념관,NaN,NaN,콘서트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1913,"축제소극장 [창원](구. 창원아트팩토리), 만수아트홀",NaN,NaN,만수아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1914,"축제소극장 [창원](구. 창원아트팩토리), 만수아트홀",NaN,NaN,"만수아트홀, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1915,춘천인형극장,NaN,NaN,"하늘극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0
1916,춘천인형극장,NaN,NaN,"하늘극장, 바우극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0
1917,춘천인형극장,NaN,NaN,"하늘극장, 코코극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,4.0,0.0,0.0,4.0
1918,티오엠씨어터(구. 문화공간필링),NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1919,파주 프로방스 마술극장,NaN,NaN,파주 프로방스 마술극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1920,"파주 프로방스 마술극장, 맛있는 극장",NaN,NaN,"파주 프로방스 마술극장, 맛있는 극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1921,포천반월아트홀,NaN,NaN,"소극장, 대극장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1922,폼텍웍스홀,NaN,NaN,폼텍웍스홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1923,"하마씨어터(구. 가든씨어터), 대학로 극장가게 (구. 문씨어터, 지구인씨어터)",NaN,NaN,"하마씨어터(구. 가든씨어터), 문씨어터 (구. 지구인씨어터)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1924,"하마씨어터(구. 가든씨어터), 세종문화회관, 드림시어터 [대학로]",NaN,NaN,"하마씨어터(구. 가든씨어터), S씨어터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1925,"한국소리문화의전당, 전북대학교 삼성문화회관",NaN,NaN,"모악당, 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1926,한성아트홀(구. 인켈아트홀),NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1927,"해바라기소극장(구. 훈아트홀), 해바라기소극장 [부산]",NaN,NaN,"해바라기소극장(구. 훈아트홀), 해바라기소극장 [부산]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1928,현대백화점 문화홀 [대구],NaN,NaN,"토파즈홀, 문화홀",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1929,"현대백화점 문화홀 [킨텍스], 솔가람아트홀",NaN,NaN,"문화홀 (9층), 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1930,"홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...",NaN,NaN,"홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1931,All,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,853.0,817.0,3350.0,654.0,2840.0,369.0,5056.0,13939.0

In [225]:
merged_out.name[1930]

'홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA Theatre)'

In [226]:
show[show.place == '홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA Theatre)']

,place,theater,name,genre
6468,"홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...","홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...",난타(NANTA) [방콕],뮤지컬
9580,"홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...","홍대난타극장(구. 뮤직쇼웨딩 전용관), 방콕 난타씨어터 (Bangkok NANTA ...",난타(NANTA) [방콕],뮤지컬

명작극장 (구 아츠플레이씨어터) / 명작극장 (구 아츠플레이씨어터), 마루아트홀 / 유앤아이센터 (화성아트홀) /

In [25]:
theater[theater.name == '명작극장 (구 아츠플레이씨어터)']

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat
1382,명작극장 (구 아츠플레이씨어터),3,553,명작극장 (구 아츠플레이씨어터),173,민간(대학로),2017,서울,종로구,서울특별시 종로구 대학로8가길 30,29.0,48.0,1.0,1.0,207.0,7.0,11.0,701.0,246.0,서울특별시 종로구 대학로8가길 30,127.002561,37.582294
1383,명작극장 (구 아츠플레이씨어터),3,553,1관,180,민간(대학로),2017,서울,종로구,서울특별시 종로구 대학로8가길 30,29.0,48.0,1.0,1.0,207.0,7.0,11.0,701.0,246.0,서울특별시 종로구 대학로8가길 30,127.002561,37.582294
1384,명작극장 (구 아츠플레이씨어터),3,553,2관,200,민간(대학로),2017,서울,종로구,서울특별시 종로구 대학로8가길 30,29.0,48.0,1.0,1.0,207.0,7.0,11.0,701.0,246.0,서울특별시 종로구 대학로8가길 30,127.002561,37.582294

In [18]:
show[show.place == '명작극장 (구 아츠플레이씨어터), 마루아트홀']

                          place theater       name genre
9409   명작극장 (구 아츠플레이씨어터), 마루아트홀   마루아트홀  나의 PS 파트너    연극
9413   명작극장 (구 아츠플레이씨어터), 마루아트홀   마루아트홀    어린왕자의 꿈   뮤지컬
12374  명작극장 (구 아츠플레이씨어터), 마루아트홀   마루아트홀  나의 PS 파트너    연극
12718  명작극장 (구 아츠플레이씨어터), 마루아트홀   마루아트홀    어린왕자의 꿈   뮤지컬

In [24]:
a = show[show.place == '명작극장 (구 아츠플레이씨어터)']
b = a.pivot_table(index=['place','theater'], columns='genre', aggfunc='count', margins=True).reset_index()
b.columns = ['place','theater', 'musical', 'play', 'total']
b

               place                theater  musical  play  total
0  명작극장 (구 아츠플레이씨어터)                     1관     10.0   1.0     11
1  명작극장 (구 아츠플레이씨어터)                 2관, 1관      1.0   NaN      1
2  명작극장 (구 아츠플레이씨어터)      명작극장 (구 아츠플레이씨어터)      6.0   2.0      8
3  명작극장 (구 아츠플레이씨어터)  명작극장 (구 아츠플레이씨어터), 1관      4.0   NaN      4
4  명작극장 (구 아츠플레이씨어터)  명작극장 (구 아츠플레이씨어터), 2관      7.0   1.0      8
5                All                            28.0   4.0     32

In [28]:
b.loc[0,:] = ['명작극장 (구 아츠플레이씨어터)', '1관', 15, 1, 16]
b.loc[1,:] = ['명작극장 (구 아츠플레이씨어터)', '2관', 8, 1, 9]
b.loc[2,:] = ['명작극장 (구 아츠플레이씨어터)', '명작극장 (구 아츠플레이씨어터)', 17, 3, 20]

c = [3,4,5]

b = b.drop(c)
b

               place            theater  musical  play  total
0  명작극장 (구 아츠플레이씨어터)                 1관     15.0   1.0     16
1  명작극장 (구 아츠플레이씨어터)                 2관      8.0   1.0      9
2  명작극장 (구 아츠플레이씨어터)  명작극장 (구 아츠플레이씨어터)     17.0   3.0     20

In [30]:
for i in ['korea_opera', 'dance', 'compound', 'opera','classic']:
    b[i] = [0,0,0]
    
b = b[['place','theater','korea_opera','dance','musical','compound','play','opera','classic','total']]
b

,place,theater,korea_opera,dance,musical,compound,play,opera,classic,total
0,명작극장 (구 아츠플레이씨어터),1관,0,0,15.0,0,1.0,0,0,16
1,명작극장 (구 아츠플레이씨어터),2관,0,0,8.0,0,1.0,0,0,9
2,명작극장 (구 아츠플레이씨어터),명작극장 (구 아츠플레이씨어터),0,0,17.0,0,3.0,0,0,20

In [32]:
b.columns = ['name','theater_name','korea_opera','dance','musical','compound','play','opera','classic','total']

In [31]:
df = pd.read_csv('df_merge_real_final.csv')
df.tail()

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
1840,후용공연예술센터,2,320,교실극장,120,민간(대학로 외),2001,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0
1841,후용공연예술센터,2,320,야외공연장,200,민간(대학로 외),2001,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1842,흰물결아트센터,3,978,화이트홀,475,민간(대학로 외),2007,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,1.0,2.0,0.0,0.0,0.0,2.0,5.0
1843,흰물결아트센터,3,978,아트홀,200,민간(대학로 외),2007,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1844,흰물결아트센터,3,978,예술극장,303,민간(대학로 외),2007,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0

In [35]:
df[df.name == '명작극장 (구 아츠플레이씨어터)']

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
1382,명작극장 (구 아츠플레이씨어터),3,553,명작극장 (구 아츠플레이씨어터),173,민간(대학로),2017,서울,종로구,서울특별시 종로구 대학로8가길 30,29.0,48.0,1.0,1.0,207.0,7.0,11.0,701.0,246.0,서울특별시 종로구 대학로8가길 30,127.002561,37.582294,0.0,0.0,17.0,0.0,3.0,0.0,0.0,20.0
1383,명작극장 (구 아츠플레이씨어터),3,553,1관,180,민간(대학로),2017,서울,종로구,서울특별시 종로구 대학로8가길 30,29.0,48.0,1.0,1.0,207.0,7.0,11.0,701.0,246.0,서울특별시 종로구 대학로8가길 30,127.002561,37.582294,0.0,0.0,15.0,0.0,1.0,0.0,0.0,16.0
1384,명작극장 (구 아츠플레이씨어터),3,553,2관,200,민간(대학로),2017,서울,종로구,서울특별시 종로구 대학로8가길 30,29.0,48.0,1.0,1.0,207.0,7.0,11.0,701.0,246.0,서울특별시 종로구 대학로8가길 30,127.002561,37.582294,NaN,NaN,8.0,NaN,1.0,NaN,NaN,9.0

In [34]:
df.musical[1382] = 17
df.play[1382] = 3
df.total[1382] = 20
df.musical[1383] = 15
df.play[1383] = 1
df.total[1383] = 16
df.musical[1384] = 8
df.play[1384] = 1
df.total[1384] = 9

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys
C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  if __name__ == '__main__':

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1845 entries, 0 to 1844
Data columns (total 30 columns):
name            1845 non-null object
n_theater       1845 non-null int64
n_seats         1845 non-null int64
theater_name    1845 non-null object
n_seats2        1845 non-null object
attr            1845 non-null object
open            1845 non-null int64
city            1845 non-null object
gu              1845 non-null object
address         1845 non-null object
CS2             1845 non-null float64
PK6             1845 non-null float64
OL7             1845 non-null float64
SW8             1845 non-null float64
CT1             1845 non-null float64
AT4             1845 non-null float64
AD5             1845 non-null float64
FD6             1845 non-null float64
CE7             1845 non-null float64
addr            1845 non-null object
lng             1845 non-null float64
lat             1845 non-null float64
korea_opera     1149 non-null float64
dance           1149 non-null float64
musical         1150 non-null float64
compound        1149 non-null float64
play            1150 non-null float64
opera           1149 non-null float64
classic         1149 non-null float64
total           1150 non-null float64
dtypes: float64(19), int64(3), object(8)
memory usage: 432.5+ KB

In [37]:
df = df.fillna(0)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1845 entries, 0 to 1844
Data columns (total 30 columns):
name            1845 non-null object
n_theater       1845 non-null int64
n_seats         1845 non-null int64
theater_name    1845 non-null object
n_seats2        1845 non-null object
attr            1845 non-null object
open            1845 non-null int64
city            1845 non-null object
gu              1845 non-null object
address         1845 non-null object
CS2             1845 non-null float64
PK6             1845 non-null float64
OL7             1845 non-null float64
SW8             1845 non-null float64
CT1             1845 non-null float64
AT4             1845 non-null float64
AD5             1845 non-null float64
FD6             1845 non-null float64
CE7             1845 non-null float64
addr            1845 non-null object
lng             1845 non-null float64
lat             1845 non-null float64
korea_opera     1845 non-null float64
dance           1845 non-null float64
musical         1845 non-null float64
compound        1845 non-null float64
play            1845 non-null float64
opera           1845 non-null float64
classic         1845 non-null float64
total           1845 non-null float64
dtypes: float64(19), int64(3), object(8)
memory usage: 432.5+ KB

In [231]:
idx = [4421, 2471,6652,6957,6979, 6464, 5764, 9485, 7792,7802,9945,12527,12531,13515, 3510, 3887,
      1132,2068,3385,4108,5566,6845,9622, 2298,5680, 6513,9583, 2678,6785, 3995, 2374,7956,13852,
      1963, 5750, 9383,11019, 9444,13919, 6450, 8967, 3820, 8104, 6384, 4439, 8757, 4221, 12588,
      9534, 8984,4969, 6808, 573, 6026, 4585, 1583,3758, 6385, 2399,5587, 13166, 11624, 8,23,3445,3447,3449,3516,
      10,2588,3043,3451, 2541,2831,3446,3694, 8152, 5179, 5341, 9046, 8369, 6603, 8103, 5934, 6468,9580]

In [ ]:
토파즈홀, 문화홀

In [ ]:
df2.iloc[82,0] = '그랜드힐튼호텔'
df2.iloc[82,1] = '컨벤션홀'

In [228]:
df2.loc[150,:] = show.loc[5934,:]
df2.iloc[150,1] = '문화홀'
df2.loc[151,:] = show.loc[6468,:]
df2.iloc[151,0] = '홍대난타극장(구. 뮤직쇼웨딩 전용관)'
df2.iloc[151,1] = '홍대난타극장(구. 뮤직쇼웨딩 전용관)'
df2.loc[152,:] = show.loc[9580,:]
df2.iloc[152,0] = '홍대난타극장(구. 뮤직쇼웨딩 전용관)'
df2.iloc[152,1] = '홍대난타극장(구. 뮤직쇼웨딩 전용관)'

df2[150:160]

                    place               theater              name genre
150        현대백화점 문화홀 [대구]                   문화홀  강철소방대 파이어로보 [대구]   뮤지컬
151  홍대난타극장(구. 뮤직쇼웨딩 전용관)  홍대난타극장(구. 뮤직쇼웨딩 전용관)    난타(NANTA) [방콕]   뮤지컬
152  홍대난타극장(구. 뮤직쇼웨딩 전용관)  홍대난타극장(구. 뮤직쇼웨딩 전용관)    난타(NANTA) [방콕]   뮤지컬
153                   NaN                   NaN               NaN   NaN
154                   NaN                   NaN               NaN   NaN
155                   NaN                   NaN               NaN   NaN
156                   NaN                   NaN               NaN   NaN
157                   NaN                   NaN               NaN   NaN
158                   NaN                   NaN               NaN   NaN
159                   NaN                   NaN               NaN   NaN

In [229]:
df2 = df2.dropna(axis=0)
df2.shape

(144, 4)

In [230]:
df2[0:100]

,place,theater,name,genre
0,BNK부산은행 조은극장,1관,불편한 타이밍 [부산],연극
1,BNK부산은행 조은극장,2관,불편한 타이밍 [부산],연극
2,가온아트홀 [부산],1관,마음의 연주,연극
3,가온아트홀 [부산],2관,마음의 연주,연극
4,경기상상캠퍼스 M3,멀티벙커,"경기인형극제, 목수장이 엘리 [수원]",연극
5,경기상상캠퍼스 M3,공간1986,"경기인형극제, 목수장이 엘리 [수원]",연극
6,경기상상캠퍼스 M3,교육1964,"경기인형극제, 평강공주와 온달바보 [수원]",연극
7,경기상상캠퍼스 M3,공간1986,"경기인형극제, 평강공주와 온달바보 [수원]",연극
8,경기상상캠퍼스 M3,멀티벙커,"경기인형극제, 드래곤",연극
9,경기상상캠퍼스 M3,공간1986,"경기인형극제, 드래곤",연극
10,고양어울림누리,어울림극장,"헤이지니&럭키강이 시즌2, 비밀의 문 [고양]",뮤지컬
11,고양아람누리,아람극장,"헤이지니&럭키강이 시즌2, 비밀의 문 [고양]",뮤지컬
12,과천시민회관,소극장,공룡애니멀쇼 [과천],복합
13,과천시민회관,대극장,공룡애니멀쇼 [과천],복합
14,김천시문화예술회관,대공연장,"제16회 김천국제가족연극제, 더 로켓",연극
15,김천시립문화회관,김천시립문화회관,"제16회 김천국제가족연극제, 더 로켓",연극
16,노원어울림극장,노원어울림극장,"허풍선이 과학쇼 시즌2, 마리퀴리 vs 아인슈타인",뮤지컬
17,노원어울림극장,노원어울림극장,오버코트,연극
18,노원어울림극장,노원어울림극장,성민제X대니구 듀오 콘서트,클래식
19,노원어울림극장,노원어울림극장,음악칼럼니스트 장일범과 함께하는 양성원 피아노 리사이틀,클래식
20,노원어울림극장,노원어울림극장,신지아 바이올린 리사이틀,클래식
21,노원어울림극장,노원어울림극장,A FOREVER FRIEND,뮤지컬
22,당진문예의전당,소공연장,겨울이야기 [당진],뮤지컬
23,당진문예의전당,대공연장,겨울이야기 [당진],뮤지컬
24,대구콘서트하우스,챔버홀(소공연장),제2회 매드라인 정기연주회,클래식
25,대구콘서트하우스,그랜드홀(대공연장),제2회 매드라인 정기연주회,클래식
26,대백프라자,프라임홀,구둣방 할아버지와 꼬마 산타,뮤지컬
27,대백프라자,레오문화홀,구둣방 할아버지와 꼬마 산타,뮤지컬
28,대백프라자,프라임홀,팥죽할멈과 호랑이 [대구],뮤지컬
29,대백프라자,레오문화홀,팥죽할멈과 호랑이 [대구],뮤지컬
30,대백프라자,프라임홀,알라딘과 요술램프 [대구],연극
31,대백프라자,레오문화홀,알라딘과 요술램프 [대구],연극
32,대백프라자,프라임홀,헨젤과 그레텔 [대구],연극
33,대백프라자,레오문화홀,헨젤과 그레텔 [대구],연극
34,대백프라자,프라임홀,용궁이야기,연극
35,대백프라자,레오문화홀,용궁이야기,연극
36,대백프라자,프라임홀,황금알을 낳는 암탉 & 애벌레의 꿈,연극
37,대백프라자,레오문화홀,황금알을 낳는 암탉 & 애벌레의 꿈,연극
38,대전 대덕구 청소년수련관,대전 대덕구 청소년수련관,공룡애니멀쇼 [대전],복합
39,대덕청소년수련관,강당,공룡애니멀쇼 [대전],복합
40,대전평송청소년문화센터,대극장,앨리스 인 원더랜드 [대전],뮤지컬
41,대전평송청소년문화센터,소극장,꼬마공주소피아 시즌2: 도심여행편 [대전],뮤지컬
42,대학로스타시티,타이니앨리스 (구 아트홀 마리카2관),그녀를 믿지 마세요,연극
43,KBS 수원아트홀,KBS 수원아트홀,그녀를 믿지 마세요,연극
44,더케이아트홀,더케이아트홀,산타와 월드스타 뽀로로,뮤지컬
45,더케이아트홀,더케이아트홀,런닝맨: 마지막 승자 [서울(앵콜)],뮤지컬
46,동래문화회관,소극장,파 한단 두부 한 모,연극
47,동래문화회관,대극장,파 한단 두부 한 모,연극
48,디큐브아트센터,스페이스 신도림,그리스,뮤지컬
49,디큐브아트센터,디큐브씨어터,그리스,뮤지컬
50,디큐브아트센터,스페이스 신도림,여명의 눈동자,뮤지컬
51,디큐브아트센터,디큐브씨어터,여명의 눈동자,뮤지컬
52,디큐브아트센터,스페이스 신도림,빌리 엘리어트,뮤지컬
53,디큐브아트센터,디큐브씨어터,빌리 엘리어트,뮤지컬
54,레몬트리소극장,레몬트리소극장,소믈리에 [가온아트홀],연극
55,가온아트홀 [부산],1관,소믈리에 [가온아트홀],연극
56,문경문화예술회관,문화아트홀,썸머콘서트 IN 문경,클래식
57,문경문화예술회관,대공연장,썸머콘서트 IN 문경,클래식
58,미마지아트센터,풀빛극장(오아시스극장),와일드패밀리,연극
59,미마지아트센터,눈빛극장,와일드패밀리,연극
60,미마지아트센터,풀빛극장(오아시스극장),와일드패밀리,연극
61,미마지아트센터,눈빛극장,와일드패밀리,연극
62,봄날아트홀(구. 아리랑소극장),2관(지하2층),크리미널,연극
63,봄날아트홀(구. 아리랑소극장),1관(지하1층),크리미널,연극
64,봄날아트홀(구. 아리랑소극장),2관(지하2층),크리미널,연극
65,봄날아트홀(구. 아리랑소극장),1관(지하1층),크리미널,연극
66,부산문화회관,중극장,"(재)부산문화회관과 함께하는 마티네콘서트 시즌5, 오페라 이야기Ⅲ",오페라
67,부산문화회관,대극장,"(재)부산문화회관과 함께하는 마티네콘서트 시즌5, 오페라 이야기Ⅲ",오페라
68,부천시민회관,대공연장,렛잇고 [부천],뮤지컬
69,미마지아트센터,풀빛극장(오아시스극장),렛잇고 [부천],뮤지컬
70,부평아트센터,해누리극장,공룡애니멀쇼 [부평],뮤지컬
71,부평아트센터,달누리극장,공룡애니멀쇼 [부평],뮤지컬
72,브러쉬씨어터,공연장,두들팝,연극
73,서산시문화회관,소공연장,그놈은 예뻤다 [서산],연극
74,서산시문화회관,대공연장,그놈은 예뻤다 [서산],연극
75,서울주문화센터,대공연장,빨래,뮤지컬
76,동양예술극장(구. 아트센터K),1관(네모극장),빨래,뮤지컬
77,세라믹팔레스홀,세라믹팔레스홀,백설공주와 일곱난쟁이 [당진],뮤지컬
78,당진문예의전당,대공연장,백설공주와 일곱난쟁이 [당진],뮤지컬
79,수성아트피아,용지홀,세계 명곡과 함께하는 예술가곡의 밤 [대구],클래식
80,수성아트피아,무학홀,세계 명곡과 함께하는 예술가곡의 밤 [대구],클래식
90,올림픽공원,KSPO DOME(체조경기장),요요 마 바흐 프로젝트,클래식
91,울산문화예술회관,대공연장,제40회 울산시립청소년교향악단 정기연주회,클래식
92,울산문화예술회관,소공연장,"전원경의 그림 콘서트, 스페인 안달루시아",복합
93,울진문화예술회관,울진문화예술회관,캐릭터 프린세스: 황금열쇠를 찾아서 [울진],뮤지컬
94,울진군문화센터,울진군문화센터,캐릭터 프린세스: 황금열쇠를 찾아서 [울진],뮤지컬
95,윤당아트홀,1관,레미제라블 코제트 소녀 이야기,뮤지컬
96,윤당아트홀,2관,레미제라블 코제트 소녀 이야기,뮤지컬
97,윤당아트홀,1관,팥죽할멈과 글모르는 호랑이,뮤지컬
98,윤당아트홀,2관,팥죽할멈과 글모르는 호랑이,뮤지컬
99,인제하늘내린센터,대극장,"제16회 평창대관령음악제, 페스티벌 오케스트라",클래식
100,알펜시아 리조트,뮤직텐트,"제16회 평창대관령음악제, 페스티벌 오케스트라",클래식
101,인천문화예술회관,소공연장,"얼리 윈터페스티벌, Harmony Of Light",복합
102,인천문화예술회관,대공연장,"해설이 있는 음악회 썸머페스티벌, 로미오와 줄리엣",클래식
103,제주문예회관,대극장,엉뚱발랄 콩순이 : 엄마편 [은평],뮤지컬
104,은평문화예술회관,공연장,엉뚱발랄 콩순이 : 엄마편 [은평],뮤지컬
105,축제소극장 [창원](구. 창원아트팩토리),1관,흉터 [창원],연극
106,만수아트홀,만수아트홀,흉터 [창원],연극
107,춘천인형극장,하늘극장,어느 한 아부지,연극
108,춘천인형극장,대극장,어느 한 아부지,연극

In [233]:
show1 = show.copy()
show1 = show1.drop(idx)

In [234]:
show1.index = range(len(show1))

In [244]:
show_final = pd.concat([show1, df2])
show_final.index = range(len(show_final.index))
show_final.shape

(13997, 4)

In [245]:
show1 = show_final.copy()

In [246]:
show_genre = show1.pivot_table(index=['place','theater'], columns='genre', aggfunc='count', margins=True).reset_index()
show_genre.head()

                    place             theater name                            \
genre                                           국악   무용   뮤지컬   복합   연극  오페라
0               (재)경기문화재단                 다산홀  NaN  NaN   NaN  NaN  1.0  NaN
1                (재)영화의전당           비프씨어터(야외)  NaN  NaN   NaN  NaN  NaN  NaN
2                (재)영화의전당               하늘연극장  2.0  7.0   2.0  5.0  4.0  1.0
3        2001 아울렛키즈홀 [구로]    2001 아울렛키즈홀 [구로]  NaN  NaN  16.0  2.0  1.0  NaN
4      2001 아울렛키즈홀 [수원남문]  2001 아울렛키즈홀 [수원남문]  NaN  NaN  22.0  1.0  1.0  NaN


genre   클래식 All
0       NaN   1
1       1.0   1
2      21.0  42
3       1.0  20
4       NaN  24

In [247]:
show_genre_exp = show_genre.copy()
show_genre_exp.columns = ['place','theater','korea_opera','dance','musical','compound','play','opera','classic','total']
show_genre_exp.head()

,place,theater,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,다산홀,NaN,NaN,NaN,NaN,1.0,NaN,NaN,1
1,(재)영화의전당,비프씨어터(야외),NaN,NaN,NaN,NaN,NaN,NaN,1.0,1
2,(재)영화의전당,하늘연극장,2.0,7.0,2.0,5.0,4.0,1.0,21.0,42
3,2001 아울렛키즈홀 [구로],2001 아울렛키즈홀 [구로],NaN,NaN,16.0,2.0,1.0,NaN,1.0,20
4,2001 아울렛키즈홀 [수원남문],2001 아울렛키즈홀 [수원남문],NaN,NaN,22.0,1.0,1.0,NaN,NaN,24

In [248]:
show_genre_exp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1184 entries, 0 to 1183
Data columns (total 10 columns):
place          1184 non-null object
theater        1184 non-null object
korea_opera    198 non-null float64
dance          204 non-null float64
musical        681 non-null float64
compound       325 non-null float64
play           632 non-null float64
opera          125 non-null float64
classic        384 non-null float64
total          1184 non-null int64
dtypes: float64(7), int64(1), object(2)
memory usage: 92.6+ KB

In [249]:
show_genre_exp = show_genre_exp.fillna(0)
show_genre_exp.head()

,place,theater,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,다산홀,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1
1,(재)영화의전당,비프씨어터(야외),0.0,0.0,0.0,0.0,0.0,0.0,1.0,1
2,(재)영화의전당,하늘연극장,2.0,7.0,2.0,5.0,4.0,1.0,21.0,42
3,2001 아울렛키즈홀 [구로],2001 아울렛키즈홀 [구로],0.0,0.0,16.0,2.0,1.0,0.0,1.0,20
4,2001 아울렛키즈홀 [수원남문],2001 아울렛키즈홀 [수원남문],0.0,0.0,22.0,1.0,1.0,0.0,0.0,24

In [250]:
show_genre_exp.columns = ['name', 'theater_name', 'korea_opera', 'dance', 'musical', 'compound',
       'play', 'opera', 'classic', 'total']

In [251]:
df_merge = pd.merge(theater, show_genre_exp, on=['name','theater_name'], how='left')
print(df_merge.shape)
df_merge.head()

(1845, 30)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073,0.0,0.0,16.0,2.0,1.0,0.0,1.0,20.0
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439,0.0,0.0,22.0,1.0,1.0,0.0,0.0,24.0

In [252]:
df_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1845 entries, 0 to 1844
Data columns (total 30 columns):
name            1845 non-null object
n_theater       1845 non-null int64
n_seats         1845 non-null int64
theater_name    1845 non-null object
n_seats2        1845 non-null object
attr            1845 non-null object
open            1845 non-null int64
city            1845 non-null object
gu              1845 non-null object
address         1845 non-null object
CS2             1845 non-null float64
PK6             1845 non-null float64
OL7             1845 non-null float64
SW8             1845 non-null float64
CT1             1845 non-null float64
AT4             1845 non-null float64
AD5             1845 non-null float64
FD6             1845 non-null float64
CE7             1845 non-null float64
addr            1845 non-null object
lng             1845 non-null float64
lat             1845 non-null float64
korea_opera     1149 non-null float64
dance           1149 non-null float64
musical         1149 non-null float64
compound        1149 non-null float64
play            1149 non-null float64
opera           1149 non-null float64
classic         1149 non-null float64
total           1149 non-null float64
dtypes: float64(19), int64(3), object(8)
memory usage: 446.8+ KB

In [253]:
df_merge_out = pd.merge(theater, show_genre_exp, on=['name','theater_name'], how='outer')
print(df_merge_out.shape)
df_merge_out.head()

(1880, 30)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
0,(재)경기문화재단,1.0,154.0,다산홀,154,공공(기타),2001.0,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,1M SPACE,1.0,0.0,1M SPACE,0,민간(대학로 외),2019.0,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1m클래식아트홀,1.0,130.0,1m클래식아트홀,130,민간(대학로),2007.0,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2001 아울렛키즈홀 [구로],1.0,100.0,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017.0,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073,0.0,0.0,16.0,2.0,1.0,0.0,1.0,20.0
4,2001 아울렛키즈홀 [수원남문],1.0,100.0,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005.0,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439,0.0,0.0,22.0,1.0,1.0,0.0,0.0,24.0

In [254]:
df_merge_out.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1880 entries, 0 to 1879
Data columns (total 30 columns):
name            1880 non-null object
n_theater       1845 non-null float64
n_seats         1845 non-null float64
theater_name    1880 non-null object
n_seats2        1845 non-null object
attr            1845 non-null object
open            1845 non-null float64
city            1845 non-null object
gu              1845 non-null object
address         1845 non-null object
CS2             1845 non-null float64
PK6             1845 non-null float64
OL7             1845 non-null float64
SW8             1845 non-null float64
CT1             1845 non-null float64
AT4             1845 non-null float64
AD5             1845 non-null float64
FD6             1845 non-null float64
CE7             1845 non-null float64
addr            1845 non-null object
lng             1845 non-null float64
lat             1845 non-null float64
korea_opera     1184 non-null float64
dance           1184 non-null float64
musical         1184 non-null float64
compound        1184 non-null float64
play            1184 non-null float64
opera           1184 non-null float64
classic         1184 non-null float64
total           1184 non-null float64
dtypes: float64(22), object(8)
memory usage: 455.3+ KB

In [255]:
df_merge_out.tail(70)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
1810,한국의집,2.0,296.0,중정마당,150,공공(기타),1981.0,서울,중구,서울특별시 중구 퇴계로36길 10,37.0,55.0,2.0,2.0,7.0,2.0,47.0,637.0,158.0,서울특별시 중구 퇴계로36길 10,126.994498,37.560224,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1811,한국전통문화전당,2.0,728.0,공연장,228,공공(기타),2015.0,전북,전주시,전라북도 전주시 완산구 현무1길 20,20.0,29.0,1.0,0.0,20.0,9.0,87.0,324.0,128.0,전라북도 전주시 완산구 현무1길 20,127.148231,35.820566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1812,한국전통문화전당,2.0,728.0,야외마당,500,공공(기타),2015.0,전북,전주시,전라북도 전주시 완산구 현무1길 20,20.0,29.0,1.0,0.0,20.0,9.0,87.0,324.0,128.0,전라북도 전주시 완산구 현무1길 20,127.148231,35.820566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1813,한라아트홀,3.0,1311.0,대극장,831,민간(대학로 외),2001.0,제주,제주시,제주특별자치도 제주시 한라대학로 38,10.0,3.0,2.0,0.0,2.0,0.0,2.0,73.0,29.0,제주특별자치도 제주시 한라대학로 38,126.474152,33.476790,0.0,0.0,5.0,0.0,0.0,0.0,0.0,5.0
1814,한라아트홀,3.0,1311.0,다목적홀,240,민간(대학로 외),2001.0,제주,제주시,제주특별자치도 제주시 한라대학로 38,10.0,3.0,2.0,0.0,2.0,0.0,2.0,73.0,29.0,제주특별자치도 제주시 한라대학로 38,126.474152,33.476790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1815,한라아트홀,3.0,1311.0,소극장,240,민간(대학로 외),2001.0,제주,제주시,제주특별자치도 제주시 한라대학로 38,10.0,3.0,2.0,0.0,2.0,0.0,2.0,73.0,29.0,제주특별자치도 제주시 한라대학로 38,126.474152,33.476790,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1816,한성아트홀(구. 인켈아트홀),2.0,390.0,2관,150,민간(대학로),1990.0,서울,종로구,서울특별시 종로구 창경궁로 254,31.0,43.0,1.0,1.0,198.0,8.0,16.0,696.0,249.0,서울특별시 종로구 창경궁로 254,126.999963,37.583743,0.0,0.0,7.0,0.0,4.0,0.0,0.0,11.0
1817,한성아트홀(구. 인켈아트홀),2.0,390.0,1관,240,민간(대학로),1990.0,서울,종로구,서울특별시 종로구 창경궁로 254,31.0,43.0,1.0,1.0,198.0,8.0,16.0,696.0,249.0,서울특별시 종로구 창경궁로 254,126.999963,37.583743,0.0,0.0,3.0,0.0,3.0,0.0,0.0,6.0
1818,한양대학교 [안산],2.0,796.0,컨퍼런스홀,560,민간(대학로 외),1979.0,경기,안산시,경기도 안산시 상록구 한양대학로 55,10.0,5.0,0.0,0.0,1.0,1.0,0.0,72.0,27.0,경기도 안산시 상록구 한양대학로 55,126.834394,37.298005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1819,한양대학교 [안산],2.0,796.0,학생회관소극장,236,민간(대학로 외),1979.0,경기,안산시,경기도 안산시 상록구 한양대학로 55,10.0,5.0,0.0,0.0,1.0,1.0,0.0,72.0,27.0,경기도 안산시 상록구 한양대학로 55,126.834394,37.298005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1820,함안문화원,2.0,626.0,대공연장,486,공공(기타),1965.0,경남,함안군,경상남도 함안군 가야읍 선왕길 1-1,2.0,7.0,0.0,0.0,5.0,0.0,0.0,3.0,0.0,경상남도 함안군 가야읍 선왕길 1-1,128.401470,35.283886,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1821,함안문화원,2.0,626.0,다목적홀,140,공공(기타),1965.0,경남,함안군,경상남도 함안군 가야읍 선왕길 1-1,2.0,7.0,0.0,0.0,5.0,0.0,0.0,3.0,0.0,경상남도 함안군 가야읍 선왕길 1-1,128.401470,35.283886,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1822,함양문화예술회관,2.0,691.0,대공연장,486,공공(문예회관),2011.0,경남,함양군,경상남도 함양군 함양읍 필봉산길 55,3.0,4.0,0.0,0.0,6.0,1.0,2.0,36.0,9.0,경상남도 함양군 함양읍 필봉산길 55,127.722273,35.524710,1.0,1.0,2.0,0.0,0.0,0.0,2.0,6.0
1823,함양문화예술회관,2.0,691.0,소공연장,205,공공(문예회관),2011.0,경남,함양군,경상남도 함양군 함양읍 필봉산길 55,3.0,4.0,0.0,0.0,6.0,1.0,2.0,36.0,9.0,경상남도 함양군 함양읍 필봉산길 55,127.722273,35.524710,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1824,해남문화예술회관,2.0,2760.0,대공연장,760,공공(문예회관),2002.0,전남,해남군,전라남도 해남군 해남읍 군청길 4,13.0,18.0,0.0,0.0,2.0,0.0,6.0,178.0,21.0,전라남도 해남군 해남읍 군청길 4,126.599065,34.573479,0.0,0.0,3.0,0.0,0.0,0.0,0.0,3.0
1825,해남문화예술회관,2.0,2760.0,야외공연장,"2,000",공공(문예회관),2002.0,전남,해남군,전라남도 해남군 해남읍 군청길 4,13.0,18.0,0.0,0.0,2.0,0.0,6.0,178.0,21.0,전라남도 해남군 해남읍 군청길 4,126.599065,34.573479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1826,해운대문화회관,2.0,588.0,해운홀,458,공공(문예회관),2007.0,부산,해운대구,부산광역시 해운대구 양운로 97,33.0,36.0,3.0,1.0,9.0,1.0,0.0,734.0,92.0,부산광역시 해운대구 양운로 97,129.173966,35.171171,2.0,2.0,14.0,3.0,2.0,4.0,17.0,44.0
1827,해운대문화회관,2.0,588.0,고운홀,130,공공(문예회관),2007.0,부산,해운대구,부산광역시 해운대구 양운로 97,33.0,36.0,3.0,1.0,9.0,1.0,0.0,734.0,92.0,부산광역시 해운대구 양운로 97,129.173966,35.171171,0.0,0.0,3.0,0.0,5.0,0.0,2.0,10.0
1828,현대백화점 문화홀 [대구],2.0,1050.0,문화홀,550,민간(대학로 외),2011.0,대구,중구,대구광역시 중구 달구벌대로 2077,36.0,58.0,0.0,2.0,22.0,10.0,31.0,761.0,208.0,대구광역시 중구 달구벌대로 2077,128.590626,35.866630,0.0,0.0,4.0,1.0,0.0,0.0,0.0,5.0
1829,현대백화점 문화홀 [대구],2.0,1050.0,토파즈홀,500,민간(대학로 외),2011.0,대구,중구,대구광역시 중구 달구벌대로 2077,36.0,58.0,0.0,2.0,22.0,10.0,31.0,761.0,208.0,대구광역시 중구 달구벌대로 2077,128.590626,35.866630,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1830,현대예술관,2.0,1174.0,대공연장,962,민간(대학로 외),1998.0,울산,동구,울산광역시 동구 명덕로 10 - 0 현대예술관,7.0,8.0,0.0,0.0,4.0,0.0,2.0,136.0,17.0,울산광역시 동구 명덕로 10 - 0 현대예술관,129.431689,35.522858,0.0,1.0,6.0,0.0,2.0,0.0,6.0,15.0
1831,현대예술관,2.0,1174.0,소공연장,212,민간(대학로 외),1998.0,울산,동구,울산광역시 동구 명덕로 10 - 0 현대예술관,7.0,8.0,0.0,0.0,4.0,0.0,2.0,136.0,17.0,울산광역시 동구 명덕로 10 - 0 현대예술관,129.431689,35.522858,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1832,현대카드 언더스테이지,2.0,375.0,스튜디오,350,민간(대학로 외),2015.0,서울,용산구,서울특별시 용산구 이태원로 246,11.0,28.0,1.0,1.0,28.0,2.0,12.0,317.0,123.0,서울특별시 용산구 이태원로 246,127.000702,37.536636,1.0,1.0,0.0,3.0,0.0,0.0,0.0,5.0
1833,현대카드 언더스테이지,2.0,375.0,Vinyl ＆ Plastic(뮤직라이브러리),25,민간(대학로 외),2015.0,서울,용산구,서울특별시 용산구 이태원로 246,11.0,28.0,1.0,1.0,28.0,2.0,12.0,317.0,123.0,서울특별시 용산구 이태원로 246,127.000702,37.536636,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1834,홍익대 대학로 아트센터,2.0,852.0,대극장,702,민간(대학로),2013.0,서울,종로구,서울특별시 종로구 대학로 57,26.0,43.0,0.0,0.0,51.0,3.0,17.0,304.0,96.0,서울특별시 종로구 대학로 57,127.001450,37.576559,0.0,0.0,9.0,0.0,0.0,0.0,0.0,9.0
1835,홍익대 대학로 아트센터,2.0,852.0,소극장,150,민간(대학로),2013.0,서울,종로구,서울특별시 종로구 대학로 57,26.0,43.0,0.0,0.0,51.0,3.0,17.0,304.0,96.0,서울특별시 종로구 대학로 57,127.001450,37.576559,0.0,0.0,0.0,0.0,17.0,0.0,0.0,17.0
1836,홍주문화회관,2.0,715.0,대공연장,615,공공(문예회관),1988.0,충남,홍성군,충청남도 홍성군 홍성읍 내포로 164,3.0,6.0,5.0,0.0,3.0,3.0,1.0,51.0,10.0,충청남도 홍성군 홍성읍 내포로 164,126.651896,36.594770,0.0,0.0,4.0,0.0,1.0,0.0,1.0,6.0
1837,홍주문화회관,2.0,715.0,소공연장,100,공공(문예회관),1988.0,충남,홍성군,충청남도 홍성군 홍성읍 내포로 164,3.0,6.0,5.0,0.0,3.0,3.0,1.0,51.0,10.0,충청남도 홍성군 홍성읍 내포로 164,126.651896,36.594770,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1838,화순 하니움 문화스포츠센터,2.0,893.0,적벽실(대강당),725,공공(기타),2009.0,전남,화순군,전라남도 화순군 학포로 2698 - 0 이용대체육관,1.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0,5.0,전라남도 화순군 학포로 2698 - 0 이용대체육관,126.968613,35.050124,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1839,화순 하니움 문화스포츠센터,2.0,893.0,만연홀(소공연장),168,공공(기타),2009.0,전남,화순군,전라남도 화순군 학포로 2698 - 0 이용대체육관,1.0,1.0,0.0,0.0,1.0,0.0,1.0,3.0,5.0,전라남도 화순군 학포로 2698 - 0 이용대체육관,126.968613,35.050124,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1840,후용공연예술센터,2.0,320.0,교실극장,120,민간(대학로 외),2001.0,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,0.0,0.0,0.0,0.0,6.0,0.0,0.0,6.0
1841,후용공연예술센터,2.0,320.0,야외공연장,200,민간(대학로 외),2001.0,강원,원주시,강원도 원주시 문막읍 비야동길 11,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,0.0,강원도 원주시 문막읍 비야동길 11,127.802248,37.273983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1842,흰물결아트센터,3.0,978.0,화이트홀,475,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,1.0,2.0,0.0,0.0,0.0,2.0,5.0
1843,흰물결아트센터,3.0,978.0,아트홀,200,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1844,흰물결아트센터,3.0,978.0,예술극장,303,민간(대학로 외),2007.0,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1845,KT&G 상상마당 라이브홀,NaN,NaN,상상마당 라이브홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1846,TPO Gallery(부산인도네시아센터),NaN,NaN,TPO Gallery(부산인도네시아센터),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1847,갤러리롤랑,NaN,NaN,갤러리롤랑,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1848,광명시 광명 5동 일대,NaN,NaN,광명 5동 일대,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1849,광운대학교 동해문화예술관,NaN,NaN,소극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1850,구름아래소극장,NaN,NaN,구름아래소극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1851,그랜드하얏트서울,NaN,NaN,그랜드 볼룸,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1852,"극장용, 국립중앙박물관",NaN,NaN,극장용,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1853,"더페이지 갤러리, 더 서울라이티움 (갤러리아포레 G층 전용관)",NaN,NaN,더페이지 갤러리,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1854,뚝섬플레이스,NaN,NaN,뚝섬플레이스,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1855,명작극장 (구 아츠플레이씨어터),NaN,NaN,"2관, 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1856,명작극장 (구 아츠플레이씨어터),NaN,NaN,"명작극장 (구 아츠플레이씨어터), 1관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4.0,0.0,0.0,0.0,0.0,4.0
1857,명작극장 (구 아츠플레이씨어터),NaN,NaN,"명작극장 (구 아츠플레이씨어터), 2관",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7.0,0.0,1.0,0.0,0.0,8.0
1858,"명작극장 (구 아츠플레이씨어터), 마루아트홀",NaN,NaN,마루아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,2.0,0.0,0.0,4.0
1859,무대륙,NaN,NaN,무대륙,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1860,문경문화예술회관,NaN,NaN,문화아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1861,"민송아트홀 (구. 브로드웨이아트홀), 굿씨어터",NaN,NaN,1관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1862,"민송아트홀 (구. 브로드웨이아트홀), 굿씨어터",NaN,NaN,2관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1863,생기 스튜디오,NaN,NaN,생기 스튜디오,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1864,서포초등학교,NaN,NaN,강당,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1865,송파브이아트홀,NaN,NaN,송파브이아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1866,"순위아트홀1관 [대학로], 순위아트홀(구. 네오아트홀) [강남]",NaN,NaN,순위아트홀1관 [대학로],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1867,스페이스바움,NaN,NaN,스페이스바움,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1868,"씨마크호텔 [강릉], 강릉아트센터(구. 강릉문화예술관)",NaN,NaN,야외공연장 아레나,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1869,우나앤쿠,NaN,NaN,우나앤쿠,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
1870,유앤아이센터 (화성아트홀),NaN,NaN,화성아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,5.0,0.0,1.0,0.0,4.0,11.0
1871,"이화여자대학교 삼성홀, 이화여자대학교 김영의홀",NaN,NaN,이화여자대학교 삼성홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1872,"익스트림씨어터 2관, 내유외강씨어터(구. 익스트림씨어터 1관)",NaN,NaN,익스트림씨어터 2관,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1873,추계예술대학교 황신덕기념관,NaN,NaN,콘서트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
1874,"축제소극장 [창원](구. 창원아트팩토리), 만수아트홀",NaN,NaN,만수아트홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0
1875,파주 프로방스 마술극장,NaN,NaN,파주 프로방스 마술극장,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2.0,0.0,0.0,0.0,0.0,2.0
1876,폼텍웍스홀,NaN,NaN,폼텍웍스홀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1877,"하마씨어터(구. 가든씨어터), 세종문화회관, 드림시어터 [대학로]",NaN,NaN,"하마씨어터(구. 가든씨어터), S씨어터",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1878,"현대백화점 문화홀 [킨텍스], 솔가람아트홀",NaN,NaN,"문화홀 (9층), 대공연장",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1879,All,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,853.0,817.0,3370.0,656.0,2872.0,370.0,5059.0,13997.0

In [38]:
df.to_csv('df_merge_real_final.csv', index=False, encoding='utf-8')

In [39]:
reserve = pd.read_csv('18_19예매수.csv')
reserve.head()

   Unnamed: 0             공연시설명             소공연장명     좌석수  공연건수  개막편수    총 예매수
0           0         (재)경기문화재단               다산홀   154.0   1.0   1.0      2.0
1           1          (재)영화의전당         비프씨어터(야외)  4000.0   0.5   0.5    402.5
2           2          (재)영화의전당             인디플러스    36.0   0.0   0.0      0.0
3           3          (재)영화의전당             하늘연극장   841.0  20.5  20.5  13609.5
4           4  2001 아울렛키즈홀 [구로]  2001 아울렛키즈홀 [구로]   100.0  19.0  19.0   2593.0

In [45]:
df[df.name == '(재)영화의전당']

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total
1071,(재)영화의전당,3,4877,하늘연극장,841,공공(문예회관),2011,부산,해운대구,부산광역시 해운대구 수영강변대로 120,11.0,7.0,0.0,1.0,20.0,1.0,0.0,308.0,72.0,부산광역시 해운대구 수영강변대로 120,129.127085,35.171037,2.0,7.0,2.0,5.0,4.0,1.0,21.0,42.0
1072,(재)영화의전당,3,4877,비프씨어터(야외),"4,000",공공(문예회관),2011,부산,해운대구,부산광역시 해운대구 수영강변대로 120,11.0,7.0,0.0,1.0,20.0,1.0,0.0,308.0,72.0,부산광역시 해운대구 수영강변대로 120,129.127085,35.171037,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1073,(재)영화의전당,3,4877,인디플러스,36,공공(문예회관),2011,부산,해운대구,부산광역시 해운대구 수영강변대로 120,11.0,7.0,0.0,1.0,20.0,1.0,0.0,308.0,72.0,부산광역시 해운대구 수영강변대로 120,129.127085,35.171037,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [51]:
reserve = reserve[['name', 'theater_name', 'n_plays', 'total_reserved']]
reserve.head()

               name      theater_name  n_plays  total_reserved
0         (재)경기문화재단               다산홀      1.0             2.0
1          (재)영화의전당         비프씨어터(야외)      0.5           402.5
2          (재)영화의전당             인디플러스      0.0             0.0
3          (재)영화의전당             하늘연극장     20.5         13609.5
4  2001 아울렛키즈홀 [구로]  2001 아울렛키즈홀 [구로]     19.0          2593.0

In [52]:
reserve.n_plays = reserve.n_plays*2
reserve.total_reserved = reserve.total_reserved*2
reserve.head()

C:\Users\Junmin\Anaconda3\lib\site-packages\pandas\core\generic.py:5208: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

               name      theater_name  n_plays  total_reserved
0         (재)경기문화재단               다산홀      2.0             4.0
1          (재)영화의전당         비프씨어터(야외)      1.0           805.0
2          (재)영화의전당             인디플러스      0.0             0.0
3          (재)영화의전당             하늘연극장     41.0         27219.0
4  2001 아울렛키즈홀 [구로]  2001 아울렛키즈홀 [구로]     38.0          5186.0

In [59]:
reserve = reserve[['name', 'theater_name', 'total_reserved']]
reserve.head()

               name      theater_name  total_reserved
0         (재)경기문화재단               다산홀             4.0
1          (재)영화의전당         비프씨어터(야외)           805.0
2          (재)영화의전당             인디플러스             0.0
3          (재)영화의전당             하늘연극장         27219.0
4  2001 아울렛키즈홀 [구로]  2001 아울렛키즈홀 [구로]          5186.0

In [60]:
for i in range(len(reserve)):
    reserve.name[i] = reserve.name[i].strip()
    reserve.theater_name[i] = reserve.theater_name[i].strip()

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\Junmin\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [61]:
print(df.shape)
print(reserve.shape)

(1845, 30)
(1391, 3)

In [69]:
df_final = pd.merge(df, reserve, on=['name','theater_name'], how='left')
print(df_final.shape)
df_final.head()

(1848, 31)

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total,total_reserved
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,4.0
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073,0.0,0.0,16.0,2.0,1.0,0.0,1.0,20.0,5186.0
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439,0.0,0.0,22.0,1.0,1.0,0.0,0.0,24.0,2326.0

In [63]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1848 entries, 0 to 1847
Data columns (total 31 columns):
name              1848 non-null object
n_theater         1848 non-null int64
n_seats           1848 non-null int64
theater_name      1848 non-null object
n_seats2          1848 non-null object
attr              1848 non-null object
open              1848 non-null int64
city              1848 non-null object
gu                1848 non-null object
address           1848 non-null object
CS2               1848 non-null float64
PK6               1848 non-null float64
OL7               1848 non-null float64
SW8               1848 non-null float64
CT1               1848 non-null float64
AT4               1848 non-null float64
AD5               1848 non-null float64
FD6               1848 non-null float64
CE7               1848 non-null float64
addr              1848 non-null object
lng               1848 non-null float64
lat               1848 non-null float64
korea_opera       1848 non-null float64
dance             1848 non-null float64
musical           1848 non-null float64
compound          1848 non-null float64
play              1848 non-null float64
opera             1848 non-null float64
classic           1848 non-null float64
total             1848 non-null float64
total_reserved    1362 non-null float64
dtypes: float64(20), int64(3), object(8)
memory usage: 462.0+ KB

In [67]:
df_final.head()

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total,total_reserved
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,4.0
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073,0.0,0.0,16.0,2.0,1.0,0.0,1.0,20.0,5186.0
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439,0.0,0.0,22.0,1.0,1.0,0.0,0.0,24.0,2326.0

In [66]:
df_final[df_final.name=='흰물결아트센터']

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total,total_reserved
1845,흰물결아트센터,3,978,화이트홀,475,민간(대학로 외),2007,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,1.0,2.0,0.0,0.0,0.0,2.0,5.0,37.0
1846,흰물결아트센터,3,978,아트홀,200,민간(대학로 외),2007,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0
1847,흰물결아트센터,3,978,예술극장,303,민간(대학로 외),2007,서울,서초구,서울특별시 서초구 반포대로 150,13.0,35.0,1.0,1.0,7.0,0.0,3.0,320.0,73.0,서울특별시 서초구 반포대로 150,127.007282,37.493433,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,22.0

In [68]:
df_exp = df_final.copy()

df_exp.drop_duplicates().shape

(1848, 31)

In [71]:
df_final.to_csv('df_merge_real_final.csv', index=False, encoding='utf-8')

In [72]:
df = pd.read_csv('df_merge_real_final.csv')
df.head()

,name,n_theater,n_seats,theater_name,n_seats2,attr,open,city,gu,address,CS2,PK6,OL7,SW8,CT1,AT4,AD5,FD6,CE7,addr,lng,lat,korea_opera,dance,musical,compound,play,opera,classic,total,total_reserved
0,(재)경기문화재단,1,154,다산홀,154,공공(기타),2001,경기,수원시,경기도 수원시 팔달구 인계로 178,25.0,27.0,1.0,0.0,12.0,2.0,25.0,464.0,78.0,경기도 수원시 팔달구 인계로 178,127.036882,37.265775,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,4.0
1,1M SPACE,1,0,1M SPACE,0,민간(대학로 외),2019,서울,서대문구,서울특별시 서대문구 연세로4길 27,58.0,69.0,1.0,2.0,18.0,5.0,93.0,1167.0,267.0,서울특별시 서대문구 연세로4길 27,126.938198,37.557601,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
2,1m클래식아트홀,1,130,1m클래식아트홀,130,민간(대학로),2007,서울,종로구,서울특별시 종로구 대학로12길 31,25.0,46.0,1.0,1.0,198.0,7.0,9.0,639.0,227.0,서울특별시 종로구 대학로12길 31,127.003608,37.582749,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
3,2001 아울렛키즈홀 [구로],1,100,2001 아울렛키즈홀 [구로],100,민간(대학로 외),2017,서울,구로구,서울특별시 구로구 중앙로1길 36,14.0,16.0,2.0,0.0,1.0,0.0,2.0,237.0,38.0,서울특별시 구로구 중앙로1길 36,126.862677,37.498073,0.0,0.0,16.0,2.0,1.0,0.0,1.0,20.0,5186.0
4,2001 아울렛키즈홀 [수원남문],1,100,2001 아울렛키즈홀 [수원남문],100,민간(대학로 외),2005,경기,수원시,경기도 수원시 팔달구 중부대로34번길 15,16.0,16.0,1.0,0.0,5.0,1.0,10.0,222.0,45.0,경기도 수원시 팔달구 중부대로34번길 15,127.021163,37.274439,0.0,0.0,22.0,1.0,1.0,0.0,0.0,24.0,2326.0